version: "3.9"

services:
  go-algorand:
    container_name: go-algorand
    image: go-algorand
    restart: unless-stopped
    environment:
      - ALGORAND_DATA=/root/node/data
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    cpus: 1.5
    volumes:
      - ./algorand_data:/root/node/data
